### ISSUE TITLE
Can not stake when i cloned shekel for creating new my coin.

### ISSUE THREAD

**Issue by devAji917** [shekeltechnologies/JewNew#5]
Hello, everyone.
i have clone shekel v1.3.0.0 for creating new coin.
i have premined, setup masternode, setup 4 seednodes. That's are ok.
but after nLastPowBlock(200), staking is not active still.
How can i solve this issue?
i have turned off firewall and wrote staking=1 in conf file.
But Not Staking.
Help me plz
my skype = rjh917@hotmail.com
![untitled](https://user-images.githubusercontent.com/36738207/50545355-edf17d00-0bc5-11e9-8b74-ae694120e7b4.png)

**Comment by Remapper** [comment]
We cannot give answers to this as it is not a problem with shekel.
